### ISSUE TITLE
Create log file

### ISSUE THREAD

**Issue by knudsvik** [knudsvik/EnergyScore#44]
As the developer I want users to send me a log file with all relevant entries when they encounter issues.

**Comment by knudsvik** [comment]
A way to enable logging with service call:
```yaml
service: logger.set_level
data:
  custom_components.energyscore: debug
```
