### ISSUE TITLE
Score is reset every day at midnight

### ISSUE THREAD

**Issue by kamaradclimber** [knudsvik/EnergyScore#57]
## Version of the custom_component

0.3.2

## Configuration

```yaml
 - platform: energyscore
    name: House Energy Score
    unique_id: a6e5f61a-0761-478a-8520-87612e0c1ea5
    price_entity: sensor.electricity_cost
    energy_entity: sensor.home_energy_meter_gen5_electric_consumed_kw
```

## Describe the bug

Score is reset to 100% everyday at midnight.
It means the only moment where score is precise is 1min before midnight.

![image](https://user-images.githubusercontent.com/503537/209445524-443d0c05-4c62-4bcb-8212-84e8ff357eb1.png)

I think the correct behavior would be to have a rolling score on the last 24h.
